# Setup
title:        Bruce's Posts 
tagline:      Bruce Mauger
baseurl:      ""
locale:       "en"

# About/contact
author:
  name:       Bruce Mauger
  url:        https://blog.brrm.io 

#Others
markdown: kramdown
