# Setup
title:        Causal Effect Boosting 
tagline:      Bruce Mauger
baseurl:      "/uplift-boosting"
locale:       "en"

# About/contact
author:
  name:       Bruce Mauger
  url:        https://brrm.io 

#Others
markdown: kramdown
